<a href="https://colab.research.google.com/github/DendaRaniaRatu/Matkul-ML-Week5/blob/main/8_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import linier algebra, eigen value, eigen vector, normalized the vectors
import numpy as np
from numpy.linalg import eigh, norm

In [2]:
#matriks ukuran mxn
A=np.array([[-5, 2, 3], [2, 5, 1], [-3, 1, -5]])

In [3]:
A.T@A

array([[38, -3,  2],
       [-3, 30,  6],
       [ 2,  6, 35]])

In [4]:
#eigen values & V
eigh(A.T@A)

(array([25., 39., 39.]), array([[ 0.26726124, -0.96362411,  0.        ],
        [ 0.80178373,  0.22237479,  0.5547002 ],
        [-0.53452248, -0.14824986,  0.83205029]]))

In [5]:
ev, V =eigh(A.T@A)

In [6]:
V

array([[ 0.26726124, -0.96362411,  0.        ],
       [ 0.80178373,  0.22237479,  0.5547002 ],
       [-0.53452248, -0.14824986,  0.83205029]])

In [7]:
V[0]

array([ 0.26726124, -0.96362411,  0.        ])

In [8]:
V[:,0]

array([ 0.26726124,  0.80178373, -0.53452248])

In [9]:
u0= A@V[:,0]/norm(A@V[:,0])
u1= A@V[:,1]/norm(A@V[:,1])
u2= A@V[:,2]/norm(A@V[:,2])

In [10]:
U=np.array([u0,u1,u2]).T

In [11]:
U.T@A@V

array([[ 5.00000000e+00,  4.61927558e-17, -5.80878766e-17],
       [-3.24483433e-16,  6.24499800e+00,  1.06687423e-16],
       [-2.24630037e-16, -1.28454465e-17,  6.24499800e+00]])

In [12]:
#pembulatan
np.round(U.T@A@V, decimals=5)

array([[ 5.   ,  0.   , -0.   ],
       [-0.   ,  6.245,  0.   ],
       [-0.   , -0.   ,  6.245]])